#!/usr/bin/env python3
from os.path import dirname, realpath, join, splitext, isfile
from sys import stderr
from os import walk, pathsep, chmod
from stat import S_IREAD, S_IRGRP, S_IROTH, S_IWRITE
import subprocess
import os
import re

def which(program):
    def is_exe(fpath):
        return os.path.isfile(fpath) and os.access(fpath, os.X_OK)

    fpath, fname = os.path.split(program)
    if fpath:
        if is_exe(program):
            return realpath(program)
    else:
        for path in os.environ.get("PATH", "").split(os.pathsep):
            exe_file = os.path.join(path, program)
            if is_exe(exe_file):
                return realpath(exe_file)
    return None

java = which( "java" )
if not java:
    exit( "Could not find java executable..." )

jarfile_name = "xml-casa-assembly-1.86.jar"
jarpath = join( dirname(dirname(realpath(__file__))), "casagui", "private", "__java__", jarfile_name )
if not isfile(jarpath):
    exit( "JAR file ('{jarfile_name}') does not exit..." )
cmd = [ java, '-jar', jarpath ]

try:
    from casatasks import xml_interface_defs
except:
    exit("Failed to find 'xml_interface_defs' in the casatasks module...")

tasks = xml_interface_defs( )
for root, dirs, files in walk( join(dirname(dirname(realpath(__file__))),'casagui') ):
    for file in files:
        if splitext(file)[1] == '.mustache':
            with open(join(root,file)) as f:
                header = [ (m.group(1), m.group(2), m.group(0)) for m in [ re.match( "^\#+\s*TASK XML\s*>\s*(\S+)(.*)", next(f) ) for _ in range(5) ] if m ]
                if len(header) > 0:
                    if len(header) != 1:
                        print( f'''Found more than one XML descriptor in '{join(root,file)}'... skipping...''', file=stderr )
                    else:
                        task = splitext(header[0][0])[0]
                        if task in tasks:
                            if not isfile( tasks[task] ):
                                print( f'''Task XML file ('{tasks[task]}') is missing... skipping '{join(root,file)}'...''', file=stderr )
                            else:
                                src = join(root,file)
                                tgt = join( root, f'''{splitext(src)[0]}.py''' )

                                args = cmd
                                if header[0][1]:
                                    args = args + header[0][1].split( )

                                line_count = 5
                                python_source = subprocess.run( args + [src, tasks[task]], stdout=subprocess.PIPE ).stdout.decode('utf-8')
                                chmod( tgt, S_IWRITE )
                                with open( tgt, "w" ) as out:
                                    for line in python_source.splitlines( ):
                                        if line_count > 0 and re.match( "^\#+\s*TASK XML\s*>\s*(\S+)(.*)", line ):
                                            line_count -= 1
                                            continue
                                        out.write( f'''{line.rstrip( )}\n''' )
                                        if line_count > 0:
                                            line_count -= 1
                                chmod( tgt, S_IREAD | S_IRGRP | S_IROTH )
                        else:
                            print( f'''The XML file for task '{task}' is not included in casatasks... skipping '{join(root,file)}'...''', file=stderr )
