name: Pylint

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#         python-version: ["3.8", "3.9", "3.10"]
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install websockets
      run: |
        pip install websockets
    - name: Install casatasks
      run: |
        pip install casatasks
    - name: Install astropy
      run: |
        pip install astropy
        pip install regions
    - name: Install bokeh
      run: |
        pip install "bokeh>=3.2"
    - name: Create dummy version file
      run: |
        touch casagui/__version__.py
        echo "__version__ = '0.0.0'" >> casagui/__version__.py
    - name: Analysing the code with pylint
      run: |
        pylint "--msg-template='{abspath}:{line:5d},{column:2d}: {msg} ({symbol})'" --rcfile=pylintrc --output-format=colorized $(git ls-files '*.py' | egrep '^casagui/')
